### PR TITLE
Add grega to CUSTOMERS file

### PR DESCRIPTION
**Pull request by GregaVrbancic**
Signed-off-by: Grega Vrbančič <grega.vrbancic@gmail.com>

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi have you applied for access?

https://github.com/openfaas/community-cluster

**Comment by GregaVrbancic** [comment]
Hi @alexellis yes I have. I have also got the invitation to OpenFaaS Slack.

**Comment by alexellis** [comment]
Please apply using the form above if you haven't already

**Comment by GregaVrbancic** [comment]
Thank you @alexellis, I have applied for access using the mentioned form.

**Pull request merged**
