### PR TITLE
UI: Dashboard - change for progress bar

### LINKED ISSUE #188: UI: Dashboard - set progress bar to green for 1/1 replicas, not red
## Expected Behaviour

The dashboard should show "ok" / green for 1/1 replicas.

## Current Behaviour

100% of max replicas i.e. 1/1 shows as red which is not a positive sign to the user.

1/1 is shown when that is the actual limit or the limit is unknown.

## Possible Solution

Suggest / make a fix or adjustment to the React code in dashboard/client/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by jaigouk**
Signed-off-by: Jaigouk Kim <ping@jaigouk.kim>

## Description

- fixes #188
- default number of maxReplicas is 20

## How Has This Been Tested?

based on https://github.com/openfaas/faas/blob/master/gateway/handlers/alerthandler.go#L21

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by kenfdev** [comment]
I think this is not just a 100% case we should be looking at. If the minReplicas is 1 and maxReplicas is 8,  and the value is 8/8, it should be red IMO.

So it is best if we could look at the min and max replicas. If the values are the same, it should be green. WDYT @alexellis ?

**Comment by alexellis** [comment]
https://github.com/openfaas/faas/blob/master/gateway/handlers/alerthandler.go#L21

@jaigouk can you do a quick update?

**Comment by jaigouk** [comment]
@alexellis let me check.

**Comment by alexellis** [comment]
LGTM

**Pull request merged**
