### PR TITLE
Add kamaln7 to CUSTOMERS file

### PR DESCRIPTION
**Pull request by kamaln7**
👋🏼

### CODE REVIEW

**Comment by alexellis** [comment]
Hey did you see the instructions on how to do this?

You'll need to do a new PR or use git to reset these commits and add them again. 

Alex

**Comment by kamaln7** [comment]
Yep I forgot to sign off the second commit fixing the merge conflict. It should be good now!

**Comment by alexellis** [comment]
Ok you still have conflicts. Please delete your branch and send a new PR. It will be easier for you.

**Comment by kamaln7** [comment]
Okay

**Pull request closed without merging**
