### PR TITLE
godoc: document Handler in each function #268

### PR DESCRIPTION
**Pull request by albertogviana**
godoc: document Handler in each function #268

Signed-off-by: Alberto Viana <albertogviana@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Please can you wrap to 72 chars?

Would be good to cover the other functions too.

**Comment by albertogviana** [comment]
@alexellis, I updated the docs and as soon as you have more functions let me know.

**Comment by ivanayov** [comment]
Looks good

**Comment by alexellis** [comment]
My mistake, I had some local commits missing from the remote side.

Please can you review the complete list at https://github.com/openfaas/openfaas-cloud#components and update the PR?

Alex

**Comment by alexellis** [comment]
@albertogviana please see above. Also you'll need to do a rebase (not merge, please don't create a merge commit)

If you need help with the Git CLI let us know.

**Comment by alexellis** [comment]
@albertogviana I can't merge your PR, please see comment above.

**Comment by alexellis** [comment]
Derek close: inactive PR

**Pull request closed without merging**
