### PR TITLE
Update CUSTOMERS

### PR DESCRIPTION
**Pull request by naisanzaa**
Add naisanza to CUSTOMERS file

Signed-off-by: Eric Jaw <naisanza@gmail.com>

## Description
It was between OpenWhisk and Knative, but I didn't like either one. Then OpenFaas was listed at the top

I got elasticsearch vibes from openfaas. Elasticsearch was built with usability in mind. 

The goal is to become "data-less." Trained models are fed events from internet noise, and no data is ever retained. The experiment is to see if privacy can be learned.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Eric, you're more likely to want to work on ML models on your local OpenFaaS cluster than on OpenFaaS Cloud, which currently has some limits to prevent abuse.

Get started with the workshop: https://docs.openfaas.com/tutorials/workshop/

Or read up on [How to Serve Data Science Models with OpenFaaS](https://www.openfaas.com/blog/python-datascience-with-openfaas/)

Alex

**Comment by alexellis** [comment]
You also have access to openfaas cloud now, and can follow the initial guide https://docs.openfaas.com/openfaas-cloud/user-guide/

**Comment by ainiml** [comment]
That was my goal with OpenFaas, not with this cloud instance. I'd imagine it's heavily restricted

I'm transitioning all my servers to OpenFaas, but wanted a cloud instance to let me immediately jump in and play with the UI and create a deployment pipeline, and see if it's easy to migrate to my cluster when it's up

And also to see how user friendly it is, and how buggy it is

**Comment by alexellis** [comment]
> And also to see how user friendly it is, and how buggy it is

That's a pretty odd thing to say. OpenFaaS is stable and used in production by many companies. I am not sure what you are getting at?

The OpenFaaS Cloud dashboard and UI is different to the local OpenFaaS UI, you can find out more in the docs -> https://docs.openfaas.com/openfaas-cloud/intro/

**Pull request closed without merging**
