### PR TITLE
added myself

### PR DESCRIPTION
**Pull request by amn41**
- I agree to the terms and conditions stated [here](https://github.com/openfaas/openfaas-cloud/blob/master/PRIVACY.md)
- I want to use the cloud to run a small experiment launching an short-lived web app on demand, if all successful I would set up my own cluster for a production use case. 
- I found openfaas by googling a bunch, something along the lines of "run docker containers serverless".

### CODE REVIEW

**Comment by alexellis** [comment]
Hi you'll also need to agree to T&C and state what your planned usage is. https://openfaas.o6s.io/join for more details

Thanks

**Comment by alexellis** [comment]
It might look better in git history if you updated your commit message too:

```
Add your-username-here to CUSTOMERS file

Signed-off-by: My Full Name <my.email@address.com>
```

This is explained in the sign-up instructions in detail. How did you decide to sign-up if you didn't read this documentation? https://openfaas.o6s.io/signup#request-access-by-pull-request

**Comment by amn41** [comment]
thanks for your patience :) did read them just not v carefully

**Comment by alexellis** [comment]
No problems. For your use of the community cluster I would highly recommend reading the rest of the document in detail. OpenFaaS Cloud is a managed service so can be self hosted or used through the service I am offering to the community. Since it is a managed service it also comes with restrictions which you should be aware of and are documented. If this is not sufficient for your purposes then you can install the project using helm and any cloud Kubernetes service within a few minutes by following a few simple steps.

**Pull request merged**
