### PR TITLE
Fix issue in dashboard with non-auth deployments

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description
A deployment that didn't have auth enabled would fail
to list functions, or pass any requests through to the
backend that were destined for the api as the new auth
put in expected a token, and didn't consider the no-auth
deployment solution.

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## How Has This Been Tested?

deployed the new dashboard, it works when i had auth enabled.
Then i removed auth from my cluster by setting auth_url to echo fn.
The dashboard now lists functions correctly when theres no cookie.

## How are existing users impacted? What migration steps/scripts do we need?
Any users not using auth will need to deploy the new dashboard container to fix the issue.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by Waterdrips** [comment]
There's no cookie. As ingress comes via the edge-router, which validates auth, if we dont have a cookie then theres no auth enabled.

**Comment by Waterdrips** [comment]
I much prefer the env var idea, I'll get this put in and updated

**Comment by alexellis** [comment]
@Waterdrips please can you rebase this?

**Comment by Waterdrips** [comment]
Fixes for this were incorporated into #556

**Pull request closed without merging**
