### PR TITLE
Update CUSTOMERS

### PR DESCRIPTION
**Pull request by mikebywater**
Add mikebywater as a customer

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Mike, this process is well documented in the sign-up page. Please take another look over the instructions?

Alex

**Comment by mikebywater** [comment]
Hi Alex

Of course, apologies for missing the sign-off I was hamfistedly trying to use the Github GUI on the run. I should have taken a bit more care. 

Cheers

Mike

**Comment by alexellis** [comment]
Not a problem. You can use the UI, but follow the instructions on what to type in if doing that.


Best way forward:

1) run the CLI command against your fork or
2) do a new PR in the UI with the signoff message

**Comment by mikebywater** [comment]
Hi Alex,

I did force push against my branch on my fork prior to commenting, it appears to have made derek slightly happier(very cool), however no issue with raising a new PR.

Cheers

Mike

**Pull request merged**
