### PR TITLE
Fixed issue with secret mount path

### PR DESCRIPTION
**Pull request by viveksyngh**
`buildshiprun` was looking for the private-key secret in a `/var/openfaas/secrets/` even if `secret_mount_path` was set to something else. This changes now uses `secret_mount_path`  to look for secrets if `secret_mount_path` other wise it look to `/var/openfaas/secrets/`

Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## How Has This Been Tested?

This has been tested on my local for Docker swarm.

## Checklist:

I have:

- [ ] updated the documentation if required
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by s8sg** [comment]
@viveksyngh as I understand the `secret_mount_path` is used when the function is being deployed. In the case of `buildshiprun` the configuration of the `gateway` in the faas `docker-compose.yml` should be effective. I guess the value of `secret_mount_path` defined in `gateway_config.yml` would be effective to the new functions being deployed via `openfaas-cloud` ( I tried to change the value of `secret_mount_path` defined in `gateway_config.yml` but it doesn't change the secrets location for the `buildshiprun`) Correct me If that understanding is wrong

**Comment by alexellis** [comment]
Hi Vivek, thanks for working on this.

This fixes one issue (honoring `secret_mount_path`) and introduces another (defaulting to the old path). The default path should now be `/var/openfaas/secrets` and not `/run/secrets`.

> This changes now uses `secret_mount_path` to look for secrets if `secret_mount_path` is set otherwise it uses to `/run/secrets/'

Please can you alter the code and report back?

Alex

**Comment by viveksyngh** [comment]
Sure. I will update this one today.

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 28, 2018 at 1:24 PM, Alex Ellis<notifications@github.com> wrote:   
Hi Vivek, thanks for working on this.

This fixes one issue (honoring secret_mount_path) and introduces another (defaulting to the old path). The default path should now be /var/openfaas/secrets and not /run/secrets.


This changes now uses secret_mount_path to look for secrets if secret_mount_path is set otherwise it uses to `/run/secrets/'


Please can you alter the code and report back?

Alex

**Comment by s8sg** [comment]
Can you please use `filepath.Join()` instead of
```go
	privateKeyPath := secretMountPath + privateKeyName
```
Otherwise It will fail if the given `secretMountPath` ends without `/`

**Comment by viveksyngh** [comment]
@alexellis  I have incorporated the changes.

**Comment by s8sg** [comment]
@viveksyngh merging this PR would create conflict for `git-status` PR again. This change is already incorporated in `github-status`. Is it possible to hold the PR?

**Comment by alexellis** [comment]
We have a rebase conflict on this now. Please check if I've already addressed this in the master code or not @viveksyngh

**Comment by viveksyngh** [comment]
I have rebased and updated this PR. This is not there in the master code.

**Comment by viveksyngh** [comment]
Closing this PR as this is no longer required. Already handled by @s8sg  PR #83.

**Pull request closed without merging**
