### PR TITLE
Improved empty state when user has no functions

### PR DESCRIPTION
**Pull request by bartsmykla**
Closes https://github.com/openfaas/openfaas-cloud/issues/236

Signed-off-by: Bart Smykla <bsmykla@vmware.com>

## Description
Full version:
image

Mobile version:
image

## How Has This Been Tested?

I have tested it by deploying it to my cluster and checked
if every state is working (when there are functions,
when there are no functions, when functions are loading)

## How are existing users impacted? What migration steps/scripts do we need?
Current users if want to see the new empty state, they need to update dashboard and redeploy it to the newest version.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by bartsmykla** [comment]
@allendjal @jaigouk what do you think?

**Comment by alexellis** [comment]
Where will the two links land?

**Comment by alexellis** [comment]
Tutorials -> workshop ?

**Comment by alexellis** [comment]
Create a function probably needs to go to the OpenFaaS Gist for the community cluster.

**Comment by alexellis** [comment]
Needs a rebase now and the link suggestions so that the first one is specific to OpenFaaS Cloud to prevent confusion.

**Comment by bartsmykla** [comment]
@alexellis do we have that gist ready, or it needs to be prepared first?

**Comment by alexellis** [comment]
You know the gist for the community cluster right? It's in #openfaas-cloud pinned as the title of the channel - it's the doc everyone is using to get started in the shared environment.

**Comment by alexellis** [comment]
@bartsmykla rebase required now.

**Comment by bartsmykla** [comment]
@alexellis link changed and branch rebased

**Comment by alexellis** [comment]
Thanks for the rebase. Let's check the links over before merging. What are they pointing at now?

**Comment by alexellis** [comment]
I think we need to work on where the links are pointing to - to be specifically about OpenFaaS Cloud. The second logo also needs to change to not be the same thing because this confusing. (advice from Allen)

**Comment by bartsmykla** [comment]
@alexellis so as we discussed I can change the second image to be the same as the first one, and do we have any suggestions which links do we want to to?

**Comment by alexellis** [comment]
Released via linked PR

**Pull request closed without merging**
