### PR TITLE
Fixing badge link

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @alexellis 

just fixing the badge link...

Cheers,
Peter

### CODE REVIEW

**Comment by spekulatius** [comment]
It really works as demonstrated in the video :+1:

**Review by alexellis — APPROVED** [review]
LGTM. Thank you for tidying this up.

**Comment by alexellis** [comment]
Thanks for the PR. Which video did you see @spekulatius? 

Do you want to join us on Slack to talk about OFC?

**Comment by spekulatius** [comment]
I've actually seen a few by now. I think it was this one: https://www.youtube.com/watch?v=ibPwVggXAFI

**Pull request merged**
