### PR TITLE
Update CUSTOMERS

### PR DESCRIPTION
**Pull request by swoldanski**
Added my user to the customers file as instructed.

### CODE REVIEW

**Comment by swoldanski** [comment]
Signed-off-by: Sebastian Woldanski <sebastian.woldanski@gmail.com>

**Comment by alexellis** [comment]
Sorry you'll need to follow the instructions given by the bot.

Alex

**Comment by swoldanski** [comment]
How to say it - too much fuss to join this community...

kind regards
Sebastian Woldanski

**Comment by alexellis** [comment]
Sorry you feel that way. If you change your mind you can A) run the single command printed out, it should take about a minute or B) you can follow the instructions we provide for signing off the commit in UI by simply writing the text in the GitHub UI, that takes no longer than what you did. 

https://github.com/openfaas/community-cluster/blob/master/docs/README.md#request-access-by-pull-request

Just curious why you didn't do either of above?

Alex

**Pull request closed without merging**
