### PR TITLE
doc(CUSTOMERS) github username added

### PR DESCRIPTION
**Pull request by rimiti**
Hello everybody,

Below a simple commit to adding my Github username into the CUSTOMERS file.

Regards, 🚀

### CODE REVIEW

**Comment by rimiti** [comment]
Hi @alexellis,

Oh sorry! It's done ;)

Dimitri,

**Comment by alexellis** [comment]
You missed the flag `-s` which signs-off the commit. Please try again.

**Comment by rimiti** [comment]
Shit, it was my default IDE Git configuration 🤭 
Finally done! 🚀

**Comment by alexellis** [comment]
Sorry about this, looks like it needs a rebase against master. I'll just do this for you to simplify things.

**Comment by rimiti** [comment]
It's not a problem @alexellis 😉

**Pull request closed without merging**
