### PR TITLE
Change node8-express to node10-express

### LINKED ISSUE #410: Move to node10-express-template for Dashboard
## Expected Behaviour

Move to node10-express-template for Dashboard

## Current Behaviour

We are using node8-express

## Possible Solution

* Update the Dockerfile
* Update the README.md file
* Use `faas template store pull` instead of `faas template pull`

### PR DESCRIPTION
**Pull request by marbar3778**
Changed node8-express-template to node10-express-template,
updated make file in accordance with node version used in node10-express-template,
updated READMEs.

Signed-off-by: Marko <marbar3778@yahoo.com>

## Description
Fixes #410 

## How Has This Been Tested?
Deployed the dashboard locally. 

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by zeerorg** [comment]
LGTM

**Comment by alexellis** [comment]
Looks good to me. I'll generate the assets and update the versions.

**Comment by alexellis** [comment]
@zeerorg please can you check if there is an impact to `ofc-boostrap` and make any updates needed as a priority?

**Comment by alexellis** [comment]
How was this tested? :-1: 

```
docker: Error response from daemon: manifest for node:10.20.0-alpine not found.
```

**Pull request merged**
