### PR TITLE
copy badge markdown to clipboard

### PR DESCRIPTION
**Pull request by jaigouk**
Signed-off-by: Jaigouk Kim <ping@jaigouk.kim>

## Description

- added react-copy-to-clipboard
- clicking well area in modal will copy the markdown
- change text input to "well" : github shows token in similar way. no text input.
- fixes 1 left over issue in #172 (copy button)

## How Has This Been Tested?

manually

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by jaigouk** [comment]
need to rebase

**Comment by jaigouk** [comment]
initially, for the badge markdown, I used input field. and then I found that it’s not ideal because if I put my cursor in it, it tried to show my past input texts in chrome. so i think it’s better to use `Well` like thingy.

I added `react-copy-to-clipboard` after researching. it seems like it can get messy with clipboard thingy. so i ended up using that lib. If there is a better way to do it, then I will try to adapt to the better solution for it. since the package is quite old.

**Comment by alexellis** [comment]
Thanks for the update. @kenfdev what are your thoughts?

**Comment by kenfdev** [comment]
I like the `well` approach. But I think it's better without the `copy` button. How about:

* just showing the `well`
* hovering above it changes the cursor to `pointer`
* click the `well` and try to copy to clipboard
* If copied, show `Copied` with a `tooltip`
* If copying is not supported, just select all of the text inside the `well`

WDYT?

I'm not sure about adding `react-copy-to-clipboard` as a dependency. What trouble did you have @jaigouk ? I know that it's a bit tricky to support all browsers, but I think we could leave those legacy ones.

**Comment by jaigouk** [comment]
https://stackoverflow.com/questions/51129888/document-execcommand-copy-dont-work-in-react
https://css-tricks.com/native-browser-copy-clipboard/
there are some issues with using `document.execCommand ('copy')`

**Comment by alexellis** [comment]
@kenfdev how are we looking now?

**Comment by kenfdev** [comment]
@jaigouk This is looking awesome! Thanks a lot. One last opinion, the tooltip looks rather strange after having a look (sorry). How about just showing a "Copied!" text in green (or some different color) Can you also select all the text inside the well (so that the user can also do ctrl+c to copy)? I think this is a common behavior for these types of elements.

copy_badge_markdown_to_clipboard_by_jaigouk_ _pull_request__208_ _openfaas_openfaas-cloud

If this is complete, I think it'll be a great experience for the user.

**Comment by jaigouk** [comment]
@kenfdev i checked github's token copy page. they don't select text. and same for aws console. 
5th-attempt-for-copying-badge
I think selecting text is not a big deal if users want to do it.

**Comment by jaigouk** [comment]
The most common pattern for this we see everyday is github's clone modal.
screen shot 2018-09-23 at 21 04 07

**Comment by alexellis** [comment]
@jaigouk thanks for working through the feedback and collaborating with the community. I'll merge and we can make any additional tweaks from there. Looks great :medal_sports:

**Comment by kenfdev** [comment]
@jaigouk Thank you very much for your thorough research and contribution.  This looks great 🎉

**Comment by jaigouk** [comment]
@kenfdev thanks. let's see how it goes and tweak this based on users' feedback

**Pull request merged**
